"""Notification Module — Repository Interfaces."""

from __future__ import annotations

from abc import ABC, abstractmethod

from app.modules.notification.domain.entities import ChannelConfig, Notification, NotificationTemplate


class ITemplateRepository(ABC):
    @abstractmethod
    async def get_by_id(self, template_id: str) -> NotificationTemplate | None: ...
    @abstractmethod
    async def get_by_category(self, tenant_id: str, category: str, channel: str) -> NotificationTemplate | None: ...
    @abstractmethod
    async def list_by_tenant(self, tenant_id: str) -> list[NotificationTemplate]: ...
    @abstractmethod
    async def create(self, template: NotificationTemplate) -> NotificationTemplate: ...
    @abstractmethod
    async def update(self, template: NotificationTemplate) -> NotificationTemplate: ...


class INotificationRepository(ABC):
    @abstractmethod
    async def get_by_id(self, notification_id: str) -> Notification | None: ...
    @abstractmethod
    async def exists_by_event(self, event_id: str, channel: str, customer_id: str) -> bool: ...
    @abstractmethod
    async def create(self, notification: Notification) -> Notification: ...
    @abstractmethod
    async def update(self, notification: Notification) -> Notification: ...
    @abstractmethod
    async def list_for_customer(self, customer_id: str, *, offset: int = 0, limit: int = 50) -> tuple[list[Notification], int]: ...
    @abstractmethod
    async def list_for_tenant(self, tenant_id: str, *, status: str | None = None, offset: int = 0, limit: int = 50) -> tuple[list[Notification], int]: ...
    @abstractmethod
    async def get_pending_retries(self, *, limit: int = 100) -> list[Notification]: ...


class IChannelConfigRepository(ABC):
    @abstractmethod
    async def get_for_tenant(self, tenant_id: str, channel: str) -> ChannelConfig | None: ...
    @abstractmethod
    async def upsert(self, config: ChannelConfig) -> ChannelConfig: ...
