"""Customer Module — Repository Interfaces."""

from __future__ import annotations

from abc import ABC, abstractmethod
from datetime import date

from app.modules.customer.domain.entities import (
    Consent,
    Customer,
    CustomerPreference,
    CustomerTag,
    LoyaltyAccount,
    LoyaltyTransaction,
    Referral,
    Review,
)


class ICustomerRepository(ABC):
    @abstractmethod
    async def get_by_id(self, customer_id: str) -> Customer | None: ...
    @abstractmethod
    async def get_by_phone(self, tenant_id: str, phone: str) -> Customer | None: ...
    @abstractmethod
    async def get_by_email(self, tenant_id: str, email: str) -> Customer | None: ...
    @abstractmethod
    async def search(self, tenant_id: str, query: str, *, offset: int = 0, limit: int = 50) -> tuple[list[Customer], int]: ...
    @abstractmethod
    async def list_by_tenant(self, tenant_id: str, *, status: str | None = None, tag: str | None = None, offset: int = 0, limit: int = 50) -> tuple[list[Customer], int]: ...
    @abstractmethod
    async def create(self, customer: Customer) -> Customer: ...
    @abstractmethod
    async def update(self, customer: Customer) -> Customer: ...
    @abstractmethod
    async def soft_delete(self, customer_id: str) -> None: ...
    @abstractmethod
    async def anonymize(self, customer_id: str) -> None: ...
    @abstractmethod
    async def update_visit_stats(self, customer_id: str, amount: int) -> None: ...


class ICustomerPreferenceRepository(ABC):
    @abstractmethod
    async def get_for_customer(self, customer_id: str) -> CustomerPreference | None: ...
    @abstractmethod
    async def upsert(self, pref: CustomerPreference) -> CustomerPreference: ...


class ICustomerTagRepository(ABC):
    @abstractmethod
    async def list_by_tenant(self, tenant_id: str) -> list[CustomerTag]: ...
    @abstractmethod
    async def create(self, tag: CustomerTag) -> CustomerTag: ...
    @abstractmethod
    async def delete(self, tag_id: str) -> None: ...


class IReviewRepository(ABC):
    @abstractmethod
    async def get_by_booking(self, booking_id: str) -> Review | None: ...
    @abstractmethod
    async def list_for_customer(self, customer_id: str) -> list[Review]: ...
    @abstractmethod
    async def list_for_professional(self, professional_id: str, *, offset: int = 0, limit: int = 50) -> tuple[list[Review], int]: ...
    @abstractmethod
    async def list_for_tenant(self, tenant_id: str, *, visible_only: bool = True, offset: int = 0, limit: int = 50) -> tuple[list[Review], int]: ...
    @abstractmethod
    async def create(self, review: Review) -> Review: ...
    @abstractmethod
    async def update(self, review: Review) -> Review: ...


class IConsentRepository(ABC):
    @abstractmethod
    async def get_for_customer(self, customer_id: str) -> list[Consent]: ...
    @abstractmethod
    async def grant(self, consent: Consent) -> Consent: ...
    @abstractmethod
    async def revoke_all(self, customer_id: str) -> None: ...


class ILoyaltyRepository(ABC):
    @abstractmethod
    async def get_for_customer(self, customer_id: str) -> LoyaltyAccount | None: ...
    @abstractmethod
    async def create(self, account: LoyaltyAccount) -> LoyaltyAccount: ...
    @abstractmethod
    async def update(self, account: LoyaltyAccount) -> LoyaltyAccount: ...
    @abstractmethod
    async def add_transaction(self, txn: LoyaltyTransaction) -> LoyaltyTransaction: ...
    @abstractmethod
    async def get_transactions(self, loyalty_id: str, *, offset: int = 0, limit: int = 50) -> tuple[list[LoyaltyTransaction], int]: ...


class IReferralRepository(ABC):
    @abstractmethod
    async def get_by_code(self, code: str) -> Referral | None: ...
    @abstractmethod
    async def list_for_referrer(self, referrer_id: str) -> list[Referral]: ...
    @abstractmethod
    async def create(self, referral: Referral) -> Referral: ...
    @abstractmethod
    async def update(self, referral: Referral) -> Referral: ...
